/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ttt } from "./Ttt";
import { TttCountArgs } from "./TttCountArgs";
import { TttFindManyArgs } from "./TttFindManyArgs";
import { TttFindUniqueArgs } from "./TttFindUniqueArgs";
import { DeleteTttArgs } from "./DeleteTttArgs";
import { TttService } from "../ttt.service";
@graphql.Resolver(() => Ttt)
export class TttResolverBase {
  constructor(protected readonly service: TttService) {}

  async _tttsMeta(
    @graphql.Args() args: TttCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ttt])
  async ttts(@graphql.Args() args: TttFindManyArgs): Promise<Ttt[]> {
    return this.service.ttts(args);
  }

  @graphql.Query(() => Ttt, { nullable: true })
  async ttt(@graphql.Args() args: TttFindUniqueArgs): Promise<Ttt | null> {
    const result = await this.service.ttt(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ttt)
  async deleteTtt(@graphql.Args() args: DeleteTttArgs): Promise<Ttt | null> {
    try {
      return await this.service.deleteTtt(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
