/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Whys } from "./Whys";
import { WhysCountArgs } from "./WhysCountArgs";
import { WhysFindManyArgs } from "./WhysFindManyArgs";
import { WhysFindUniqueArgs } from "./WhysFindUniqueArgs";
import { DeleteWhysArgs } from "./DeleteWhysArgs";
import { WhysService } from "../whys.service";
@graphql.Resolver(() => Whys)
export class WhysResolverBase {
  constructor(protected readonly service: WhysService) {}

  async _whysItemsMeta(
    @graphql.Args() args: WhysCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Whys])
  async whysItems(@graphql.Args() args: WhysFindManyArgs): Promise<Whys[]> {
    return this.service.whysItems(args);
  }

  @graphql.Query(() => Whys, { nullable: true })
  async whys(@graphql.Args() args: WhysFindUniqueArgs): Promise<Whys | null> {
    const result = await this.service.whys(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Whys)
  async deleteWhys(@graphql.Args() args: DeleteWhysArgs): Promise<Whys | null> {
    try {
      return await this.service.deleteWhys(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
